# Generated by Django 5.2.6 on 2025-10-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras',
            name='link_rtsp',
        ),
        migrations.AddField(
            model_name='cameras',
            name='porta_rtsp',
            field=models.CharField(default='na', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkrtsp',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='api.cameras'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkrtsp',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
